use std::env;
use std::path::{Path, PathBuf};
use std::process::Command;

fn build_vendored_rdma() -> String {
    eprintln!("run cmake");
    let built_in = cmake::Config::new("vendor/rdma-core")
        .define("NO_MAN_PAGES", "1")
        // cmake crate defaults CMAKE_INSTALL_PREFIX to the output directory
        //
        //   https://github.com/rust-lang/cmake-rs/blob/94da9de2ea79ab6cad572e908864a160cf4847a9/src/lib.rs#L699-L703
        //
        // this results in overly long runtime paths on docs.rs, which then fail the build. it also
        // causes sadness for users trying to build since the bindings may fail to build for the
        // same reason (see https://github.com/jonhoo/rust-ibverbs/pull/41 for what was an
        // incomplete fix).
        //
        // since we never actually _install_ anything when building here, we should be able to
        // safely set this to any short path. simply by convention we set it to `/usr`.
        .define("CMAKE_INSTALL_PREFIX", "/usr")
        .no_build_target(true)
        .build();
    built_in
        .into_os_string()
        .into_string()
        .expect("build directory path is not valid UTF-8")
}

fn update_submodule() {
    if Path::new("vendor/rdma-core/CMakeLists.txt").exists() {
        // don't touch source dir if not necessary
    } else if Path::new(".git").is_dir() {
        // initialize and update submodules
        Command::new("git")
            .args(["submodule", "update", "--init"])
            .status()
            .expect("Failed to update submodules.");
    } else {
        assert!(
            Path::new("vendor/rdma-core").is_dir(),
            "vendor source not included"
        );
    }
}

fn main() {
    // Printing any rerun-if directive replaces cargo's default whole-package
    // tracking (the script binary itself stays tracked), so each path below
    // declares its own file inputs. The environment variables are declared
    // up front because they decide which path runs.
    println!("cargo:rerun-if-env-changed=RDMA_CORE_INCLUDE_DIR");
    println!("cargo:rerun-if-env-changed=RDMA_CORE_LIB_DIR");
    println!("cargo:rerun-if-env-changed=IBVERBS_HEADER_DIR");

    // Hermetic build systems (e.g. Bazel) set IBVERBS_SYS_NO_LINK=1 to suppress
    // the link directives and supply the libraries through their own dependency
    // graph instead.
    println!("cargo:rerun-if-env-changed=IBVERBS_SYS_NO_LINK");
    let no_link = env::var("IBVERBS_SYS_NO_LINK").is_ok_and(|v| v == "1");
    if !no_link {
        println!("cargo:rustc-link-lib=ibverbs");
    }

    let efa = env::var("CARGO_FEATURE_EFA").is_ok();
    if efa && !no_link {
        // `efadv_create_qp_ex` and friends are exported from libefa.
        println!("cargo:rustc-link-lib=efa");
    }

    let rdmacm = env::var("CARGO_FEATURE_RDMACM").is_ok();
    if rdmacm && !no_link {
        // The `rdma_*` connection-manager functions are exported from librdmacm.
        println!("cargo:rustc-link-lib=rdmacm");
    }

    // With the `prebuilt-bindings` feature, targets whose bindings are
    // committed under `src/prebuilt/` skip the vendored rdma-core cmake build
    // and bindgen entirely: the committed file is copied to the location
    // `lib.rs` includes bindings from. Every prebuilt file was generated by
    // this build script from the vendored rdma-core checkout (see
    // `src/prebuilt/README.md` for regeneration instructions), and the
    // bindgen-emitted layout assertions make a stale or wrong-target file a
    // compile error rather than a runtime hazard. The feature loses to an
    // explicit RDMA_CORE_INCLUDE_DIR, and the `efa`/`rdmacm` bindings are not
    // pre-generated, so both of those cases fall back to bindgen.
    let prebuilt = env::var("CARGO_FEATURE_PREBUILT_BINDINGS").is_ok();
    if prebuilt && !efa && !rdmacm && env::var("RDMA_CORE_INCLUDE_DIR").is_err() {
        let target = env::var("TARGET").unwrap_or_default();
        let prebuilt_file = match target.as_str() {
            "x86_64-unknown-linux-gnu" => Some("bindings_x86_64_linux.rs"),
            _ => None,
        };
        if let Some(file) = prebuilt_file {
            println!("cargo:rerun-if-changed=src/prebuilt");
            let manifest_dir =
                env::var("CARGO_MANIFEST_DIR").expect("failed to get current directory");
            let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
            std::fs::copy(
                format!("{manifest_dir}/src/prebuilt/{file}"),
                out_path.join("bindings.rs"),
            )
            .expect("failed to copy pre-generated bindings");
            return;
        }
        println!(
            "cargo:warning=no pre-generated ibverbs bindings for {target}; \
             falling back to bindgen"
        );
    } else if prebuilt {
        println!(
            "cargo:warning=prebuilt ibverbs bindings do not cover \
             efa/rdmacm/RDMA_CORE_INCLUDE_DIR; falling back to bindgen"
        );
    }

    // Every remaining path reads the vendored checkout, for the headers
    // bindgen parses and, without the env overrides, the cmake build too.
    println!("cargo:rerun-if-changed=vendor/rdma-core");

    let rdma_core_include_dir = if let Ok(rdma_core_include_dir) = env::var("RDMA_CORE_INCLUDE_DIR")
    {
        let rdma_core_lib_dir = env::var("RDMA_CORE_LIB_DIR").expect(
            "When supplying RDMA_CORE_INCLUDE_DIR, you also need to supply RDMA_CORE_LIB_DIR",
        );
        println!("cargo:include={rdma_core_include_dir}");
        println!("cargo:rustc-link-search=native={rdma_core_lib_dir}");
        rdma_core_include_dir
    } else {
        // build vendor/rdma-core
        // note that we only build it to generate the bindings!
        update_submodule();
        // `build_vendored_rdma` returns OUT_DIR; the cmake crate configures and
        // builds into `{OUT_DIR}/build` and, with `no_build_target`, never runs
        // the install step. rdma-core publishes its public headers into its
        // *build* tree (`include/infiniband/...`), so that is the only include
        // directory that exists here, and the built libraries live next to it.
        // Pointing bindgen at it also guarantees the bindings are generated
        // from the vendored checkout rather than from headers that happen to
        // be installed under /usr/include on the build host.
        let out_dir = build_vendored_rdma();
        println!("cargo:include={out_dir}/build/include");
        println!("cargo:rustc-link-search=native={out_dir}/build/lib");
        format!("{out_dir}/build/include/")
    };

    let ibverbs_header_dir = if let Ok(ibverbs_header_dir) = env::var("IBVERBS_HEADER_DIR") {
        ibverbs_header_dir
    } else {
        update_submodule();
        "vendor/rdma-core/libibverbs".to_string()
    };

    // generate the bindings
    eprintln!("run bindgen");
    let mut builder = bindgen::Builder::default()
        .header(format!("{ibverbs_header_dir}/verbs.h"))
        .clang_arg(format!("-I{rdma_core_include_dir}"))
        .allowlist_function("ibv_.*")
        .allowlist_function("_ibv_.*")
        .allowlist_type("ibv_.*")
        // needed to reach the static-inline `ibv_create_cq_ex` / `ibv_create_qp_ex`, which dispatch
        // through the provider op table embedded in `verbs_context`
        .allowlist_type("verbs_context")
        // the `ibv_advise_mr_advice` / `ibv_advise_mr_flags` the public API spells are macro
        // aliases for these kernel enums, which `ibv_advise_mr` takes
        .allowlist_type("ib_uverbs_advise_mr_.*")
        .allowlist_var("IBV_LINK_LAYER_.*")
        .bitfield_enum("ibv_access_flags")
        .bitfield_enum("ibv_create_cq_wc_flags")
        .bitfield_enum("ibv_device_cap_flags")
        .bitfield_enum("ibv_odp_transport_cap_bits")
        .bitfield_enum("ibv_port_cap_flags")
        .bitfield_enum("ibv_port_cap_flags2")
        .bitfield_enum("ibv_qp_attr_mask")
        .bitfield_enum("ibv_qp_create_send_ops_flags")
        .bitfield_enum("ibv_qp_init_attr_mask")
        .bitfield_enum("ibv_qp_open_attr_mask")
        .bitfield_enum("ibv_raw_packet_caps")
        .bitfield_enum("ibv_rx_hash_fields")
        .bitfield_enum("ibv_send_flags")
        .bitfield_enum("ibv_srq_init_attr_mask")
        .bitfield_enum("ibv_wc_flags")
        .bitfield_enum("ibv_wq_attr_mask")
        .bitfield_enum("ibv_wq_flags")
        .bitfield_enum("ibv_xrcd_init_attr_mask")
        .default_enum_style(bindgen::EnumVariation::Rust {
            non_exhaustive: false,
        })
        .derive_default(true)
        .derive_debug(true)
        .prepend_enum_name(false)
        .blocklist_type("ibv_wc")
        .size_t_is_usize(true);

    if efa {
        // EFA SRD queue pairs are created through the provider's direct-verbs (`efadv`), reached
        // via `<infiniband/efadv.h>` on the same include path as `verbs.h`.
        builder = builder
            .header_contents("efadv_wrapper.h", "#include <infiniband/efadv.h>")
            .allowlist_function("efadv_.*")
            .allowlist_type("efadv_.*")
            .allowlist_var("EFADV_QP_DRIVER_TYPE_.*");
    }

    if rdmacm {
        // The RDMA connection manager lives in `<rdma/rdma_cma.h>`, which itself includes `verbs.h`
        // (guarded, so the `ibv_*` types are still emitted only once) on the same include path.
        builder = builder
            .header_contents("rdmacm_wrapper.h", "#include <rdma/rdma_cma.h>")
            .allowlist_function("rdma_.*")
            .allowlist_type("rdma_.*");
    }

    let bindings = builder.generate().expect("Unable to generate bindings");

    // write the bindings to the $OUT_DIR/bindings.rs file.
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("Could not write bindings");
}
